/**
 * Textos de interfaz (menús, botones, formulario, línea de demo) por idioma.
 * Sin dependencias: lo importan componentes de cliente y no debe arrastrar el
 * contenido editorial al navegador.
 */
export type Locale = "es" | "en";

export const ui = {
  es: {
    skipToContent: "Ir al contenido",
    shareImageAlt: "MEHI. Dale voz a tu CRM. Agentes de voz con IA.",
    homeAria: "MEHI, ir al inicio",
    mainNav: "Navegación principal",
    mobileNav: "Navegación mobile",
    openNav: "Abrir navegación",
    nav: {
      solution: "Solución",
      government: "Gobierno",
      contactCenters: "Contact centers",
      business: "Empresas",
    },
    signIn: "Ingresar",
    signInLong: "Ingresar a MEHI",
    requestDemo: "Solicitar demo",
    requestADemo: "Solicitar una demo",
    switchLanguage: { label: "English", short: "EN", aria: "View this page in English" },
    hero: {
      eyebrow: "Agentes de voz con IA para gobiernos y empresas",
      titleTop: "Dale voz a tu CRM.",
      titleBottom: "Y a todo lo que tu organización sabe.",
      talkNow: "Hablá con nuestra asesora virtual",
      seeHow: "Ver cómo funciona",
    },
    call: {
      aria: "Ejemplo de una llamada atendida por MEHI",
      title: "Llamada en curso",
      badge: "Ejemplo",
      callerLabel: "Cliente",
      agentLabel: "MEHI",
      callerLine: "Hola, quería saber cuándo me llega el pedido.",
      lookup: "Consulta en tu CRM · pedido encontrado",
      agentLine: "Sale mañana y te llega el jueves. ¿Te ayudo con algo más?",
      footer: "Si hace falta, pasa la llamada a tu equipo con todo el contexto.",
    },
    benefits: {
      aria: "Beneficios principales",
      items: [
        { title: "Atiende a toda hora", description: "De noche, el fin de semana y en los picos de llamadas." },
        { title: "Libera a tu equipo", description: "Las consultas de siempre las resuelve el agente. Las personas, los casos que las necesitan." },
        { title: "Respuestas consistentes", description: "La misma información en cada llamada, sin depender de quién atienda." },
        { title: "Nadie empieza de cero", description: "Cuando deriva, tu equipo recibe lo que la persona ya contó." },
      ],
    },
    solutions: { learnMore: "Conocer más" },
    audiences: {
      eyebrow: "Para cada organización",
      title: "Elegí por dónde empezar.",
    },
    how: {
      eyebrow: "Cómo funciona",
      title: "Tu información, con voz propia.",
      videoAria:
        "Video: el agente de voz de MEHI, qué hace, cómo trabaja una llamada y cómo está armado",
      videoUnsupported: "Tu navegador no puede reproducir este video.",
      videoCaption:
        "El agente de voz de MEHI en menos de dos minutos: qué hace, cómo trabaja una llamada y cómo está armado.",
      videoMeta: "1:47 · con subtítulos",
      stepLabel: "PASO",
      steps: [
        { number: "01", title: "Conectamos tu información", description: "Tu CRM, tus bases de conocimiento y los procedimientos que tu organización validó." },
        { number: "02", title: "El agente atiende", description: "Entiende qué necesita la persona, responde y, si hace falta, deriva a tu equipo con el contexto." },
        { number: "03", title: "Vos supervisás", description: "Cada llamada queda registrada para revisarla y mejorar la información." },
      ],
    },
    answers: {
      eyebrow: "Información validada",
      title: "Cada respuesta tiene respaldo.",
      body: "El agente responde con la información que tu organización revisó y aprobó, y te muestra de dónde salió cada respuesta. Si algo no está confirmado, lo dice y deriva.",
    },
    control: {
      eyebrow: "Control de la operación",
      title: "Todo lo que pasa en tus llamadas, a la vista.",
      body: "Métricas al momento, los motivos de cada llamada y todas las conversaciones para revisar.",
      items: [
        { title: "Métricas en tiempo real", description: "Llamadas, motivos, derivaciones y duración, al momento." },
        { title: "Cada conversación, para revisar", description: "Escuchá la llamada, leé la transcripción y mirá con qué información respondió." },
        { title: "Tu equipo interviene cuando importa", description: "Las reglas de derivación las define tu organización." },
      ],
      note: "La documentación de seguridad e infraestructura se presenta en la evaluación técnica de cada proyecto.",
    },
    start: {
      eyebrow: "Cómo se contrata",
      cta: "Ver la solución completa",
    },
    faq: {
      eyebrow: "Antes de una demo",
      title: "Preguntas frecuentes",
      asideTitle: "¿Te quedó otra duda?",
      asideBodyDemo: "Preguntásela a nuestra asesora virtual: es la misma IA que atiende llamadas y te responde ahora.",
      asideBody: "Escribinos y te respondemos con tu caso concreto.",
      asideCta: "Escribinos",
    },
    resources: {
      eyebrow: "Guías y recursos",
      title: "Para evaluar con criterio",
    },
    contact: {
      eyebrow: "Conversemos",
      title: "Dale voz a tu organización.",
      body: "Tres datos y te escribimos para mostrarte cómo MEHI trabaja con tu información y tu operación.",
      bodyDemo: "Elegí cómo seguir: hablá ahora con nuestra asesora virtual o dejanos tus datos y te escribimos.",
      talkBadge: "La forma más rápida",
      talkTitle: "Hablá con nuestra asesora virtual",
      talkBody: "Es MEHI, la misma IA que atiende llamadas. Te escucha, toma tus datos por vos y te cuenta qué podemos hacer por tu organización.",
      talkMeta: ["2 o 3 minutos", "Desde el navegador", "Sin registrarte"],
      or: "o",
      formTitle: "¿Preferís escribirnos?",
      formIntro: "Dejanos tres datos y te respondemos por correo.",
    },
    footer: {
      know: "Conocer",
      textSummary: "Resumen en texto",
      contact: "Contacto",
      home: "Inicio",
      solutions: "Soluciones",
      resources: "Recursos",
    },
    page: {
      breadcrumbAria: "Ruta de navegación",
      seeExample: "Ver recorrido ficticio",
      ctaTitleGovernment: "Conversemos sobre la atención de tu organismo",
      ctaTitle: "Conversemos sobre tu operación",
      ctaBody:
        "Contanos qué atención querés mejorar. Revisamos el proceso, la información y las integraciones necesarias para definir un alcance concreto.",
      ctaButtonGovernment: "Solicitar una demostración para mi organismo",
      related: "Seguí explorando MEHI",
      exampleEyebrow: "Ejemplo ficticio · sólo lectura",
      stepLabel: "Paso",
    },
    form: {
      fullName: "Nombre y apellido",
      organization: "Organización",
      email: "Correo",
      operation: "¿Qué atienden hoy o qué querés mejorar?",
      optional: "(opcional)",
      operationPlaceholder:
        "Por ejemplo: consultas y reclamos por teléfono, unas 400 llamadas por día.",
      honeypot: "Sitio web",
      submitting: "Enviando...",
      submit: "Quiero que me contacten",
      privacy: "Tres datos y te escribimos. Los usamos únicamente para responder tu solicitud.",
    },
    demo: {
      stop: "Terminar la conversación",
      connecting: "Conectando...",
      again: "Hablar de nuevo",
      start: "Empezar a hablar",
      agentTalking: "MEHI está hablando",
      agentListening: "MEHI te escucha",
      thanks:
        "Gracias por la charla. Si no le dejaste tus datos, completá el formulario y te escribimos.",
      preferPhone: "¿Preferís llamar por teléfono?",
      disclaimer:
        "Es una línea de demostración, no una línea de atención real. La conversación queda registrada para poder responderte.",
      contactMe: "Quiero que me contacten",
      suggestionsTitle: "Probá decirle, por ejemplo:",
      suggestions: [
        { say: "Tengo un consultorio y quiero dar turnos por teléfono." },
        { say: "En el municipio recibimos muchos reclamos de vecinos." },
        { say: "¿Cómo se contrata?" },
      ],
    },
    notFound: {
      title: "Página no encontrada",
      heading: "No encontramos esa página",
      body: "Podés conocer las soluciones de MEHI o contactarnos desde el inicio.",
      back: "Volver a MEHI",
    },
  },
  en: {
    skipToContent: "Skip to content",
    shareImageAlt: "MEHI. Give your CRM a voice. AI voice agents.",
    homeAria: "MEHI, go to home page",
    mainNav: "Main navigation",
    mobileNav: "Mobile navigation",
    openNav: "Open navigation",
    nav: {
      solution: "Solution",
      government: "Government",
      contactCenters: "Contact centers",
      business: "Businesses",
    },
    signIn: "Sign in",
    signInLong: "Sign in to MEHI",
    requestDemo: "Request a demo",
    requestADemo: "Request a demo",
    switchLanguage: { label: "Español", short: "ES", aria: "Ver esta página en español" },
    hero: {
      eyebrow: "AI voice agents for governments and businesses",
      titleTop: "Give your CRM a voice.",
      titleBottom: "And everything your organization knows.",
      talkNow: "Talk to our virtual advisor",
      seeHow: "See how it works",
    },
    call: {
      aria: "Example of a call answered by MEHI",
      title: "Call in progress",
      badge: "Example",
      callerLabel: "Customer",
      agentLabel: "MEHI",
      callerLine: "Hi, I wanted to know when my order will arrive.",
      lookup: "Checked in your CRM · order found",
      agentLine: "It ships tomorrow and arrives on Thursday. Anything else I can help with?",
      footer: "When needed, it passes the call to your team with all the context.",
    },
    benefits: {
      aria: "Key benefits",
      items: [
        { title: "Answers around the clock", description: "At night, on weekends and during call peaks." },
        { title: "Frees up your team", description: "The agent handles the usual questions. People take the cases that need them." },
        { title: "Consistent answers", description: "The same information on every call, no matter who picks up." },
        { title: "Nobody starts from scratch", description: "When it hands off, your team gets what the person already said." },
      ],
    },
    solutions: { learnMore: "Learn more" },
    audiences: {
      eyebrow: "For every organization",
      title: "Choose where to start.",
    },
    how: {
      eyebrow: "How it works",
      title: "Your information, with a voice of its own.",
      videoAria:
        "Video: MEHI's voice agent, what it does, how it handles a call and how it is built",
      videoUnsupported: "Your browser cannot play this video.",
      videoCaption:
        "MEHI's voice agent in under two minutes: what it does, how it handles a call and how it is built.",
      videoMeta: "1:40 · with subtitles",
      stepLabel: "STEP",
      steps: [
        { number: "01", title: "We connect your information", description: "Your CRM, your knowledge bases and the procedures your organization validated." },
        { number: "02", title: "The agent answers", description: "It understands what the person needs, responds and, when needed, hands off to your team with the context." },
        { number: "03", title: "You stay in control", description: "Every call is logged so you can review it and improve the information." },
      ],
    },
    answers: {
      eyebrow: "Validated information",
      title: "Every answer has a source.",
      body: "The agent answers with information your organization reviewed and approved, and shows you where each answer came from. If something is not confirmed, it says so and hands off.",
    },
    control: {
      eyebrow: "Control of the operation",
      title: "Everything that happens on your calls, in plain sight.",
      body: "Live metrics, the reason for every call and every conversation ready to review.",
      items: [
        { title: "Real-time metrics", description: "Calls, reasons, handoffs and duration, as they happen." },
        { title: "Every conversation, ready to review", description: "Listen to the call, read the transcript and see which information it answered with." },
        { title: "Your team steps in when it matters", description: "Your organization defines the handoff rules." },
      ],
      note: "Security and infrastructure documentation is presented in each project's technical evaluation.",
    },
    start: {
      eyebrow: "How to hire it",
      cta: "See the full solution",
    },
    faq: {
      eyebrow: "Before a demo",
      title: "Frequently asked questions",
      asideTitle: "Still have a question?",
      asideBodyDemo: "Ask our virtual advisor: it is the same AI that answers calls, and it replies right now (in Spanish).",
      asideBody: "Write to us and we will answer with your specific case.",
      asideCta: "Write to us",
    },
    resources: {
      eyebrow: "Guides and resources",
      title: "To evaluate with good judgment",
    },
    contact: {
      eyebrow: "Let's talk",
      title: "Give your organization a voice.",
      body: "Three details and we'll get in touch to show you how MEHI works with your information and your operation.",
      bodyDemo: "Choose how: talk to our virtual advisor right now, or leave your details and we'll write to you.",
      talkBadge: "The fastest way",
      talkTitle: "Talk to our virtual advisor",
      talkBody: "It is MEHI, the same AI that answers calls. It listens, takes your details for you and tells you what we can do for your organization.",
      talkMeta: ["2–3 minutes", "In your browser", "In Spanish for now"],
      or: "or",
      formTitle: "Prefer to write to us?",
      formIntro: "Leave three details and we'll reply by email.",
    },
    footer: {
      know: "About",
      textSummary: "Text summary",
      contact: "Contact",
      home: "Home",
      solutions: "Solutions",
      resources: "Resources",
    },
    page: {
      breadcrumbAria: "Breadcrumb",
      seeExample: "See the fictional walkthrough",
      ctaTitleGovernment: "Let's talk about your agency's citizen services",
      ctaTitle: "Let's talk about your operation",
      ctaBody:
        "Tell us which service you want to improve. We review the process, the information and the integrations needed to define a concrete scope.",
      ctaButtonGovernment: "Request a demonstration for my agency",
      related: "Keep exploring MEHI",
      exampleEyebrow: "Fictional example · read only",
      stepLabel: "Step",
    },
    form: {
      fullName: "Full name",
      organization: "Organization",
      email: "Email",
      operation: "What do you handle today, or what do you want to improve?",
      optional: "(optional)",
      operationPlaceholder: "For example: phone inquiries and complaints, about 400 calls a day.",
      honeypot: "Website",
      submitting: "Sending...",
      submit: "Contact me",
      privacy: "Three details and we'll write to you. We only use them to answer your request.",
    },
    demo: {
      stop: "End the conversation",
      connecting: "Connecting...",
      again: "Talk again",
      start: "Start talking",
      agentTalking: "MEHI is speaking",
      agentListening: "MEHI is listening",
      thanks:
        "Thanks for the chat. If you didn't leave your details, fill in the form and we'll write to you.",
      preferPhone: "Prefer to call by phone?",
      disclaimer:
        "This is a demonstration line, not a real service line. The conversation is recorded so we can get back to you.",
      contactMe: "Contact me",
      suggestionsTitle: "The line speaks Spanish. Try saying, for example:",
      suggestions: [
        { say: "Tengo un consultorio y quiero dar turnos por teléfono.", gloss: "I run a clinic and want to book appointments by phone." },
        { say: "En el municipio recibimos muchos reclamos de vecinos.", gloss: "Our municipality gets many complaints from residents." },
        { say: "¿Cómo se contrata?", gloss: "How do I hire it?" },
      ],
    },
    notFound: {
      title: "Page not found",
      heading: "We couldn't find that page",
      body: "You can explore MEHI's solutions or contact us from the home page.",
      back: "Back to MEHI",
    },
  },
} as const;

export type UiText = (typeof ui)[Locale];
